# Generated by Django 3.1.5 on 2021-01-19 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlisting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watchlisting', to='auctions.listings')),
                ('watchuser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watchuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
