# Generated by Django 3.1.5 on 2021-01-20 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watchlist',
            new_name='watchlist_db',
        ),
    ]
