# Generated by Django 3.1.5 on 2021-01-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210119_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist_db',
            name='watchactive',
            field=models.BooleanField(default=False),
        ),
    ]
