# Generated by Django 3.1.5 on 2021-02-25 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210224_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='followed',
        ),
    ]
