# Generated by Django 3.1.5 on 2021-03-20 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210301_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='fuser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
